### ISSUE TITLE
Emailadresse referenzen@tug.at

### ISSUE THREAD

**Issue by georgringer** [typo3-austria/tuga.at#15]
wäre es möglich die genannte email adresse anzulegen @jousch? oder ist hier abaton zuständig?

**Comment by josefglatz** [comment]
brauch sowieso Info von unserem Hosting-Supporter abaton. Habe bereits die Einrichtung in die Wege geleitet :-)

**Comment by josefglatz** [comment]
Done; send login credentials to @georgringer
